In [2]:
## creating 2 lists
list1=[1,2,3,4]
list2=[2,3,4,5]     

In [3]:
## By adding the values of List1 n list2
list1+list2                          # In o/p list 2 will concatenated with list 1



[1, 2, 3, 4, 2, 3, 4, 5]

In [4]:
## in case of finding the sum of their values we use for loop
for i,j in zip(list1,list2):
        print(i+j)
               #on executing this will print the sum omly and will not store the values.

3
5
7
9


In [8]:
# inorder to store the values of i+j in a list, create an empty list and use the same for loop and append the values to list3
list3=[]
for i,j in zip(list1,list2):
    list3.append(i+j)

In [9]:
#on executing it will show the sum of both lists stored in list3
list3

[3, 5, 7, 9]

In [10]:
#its a long process and to overcome these difficulties, we use another library in Python called Numpy --numerical python


## Numpy


In [11]:
# import numpy as np   numpy is denoted as np

import numpy as np

In [12]:
#numpy has arrays in it. it can overcome the limitations of list and can compute more operations than list.
#so converting list1 into n array

print(np.array(list1))                #converted list1 into an array but not stored

[1 2 3 4]


In [14]:
## so inorder to store ,it in a variable called arr1

arr1=np.array(list1)

In [15]:
arr1

array([1, 2, 3, 4])

In [16]:
###Similarly for list2 also

arr2=np.array(list2)


In [17]:
arr2

array([2, 3, 4, 5])

In [18]:
### then going to add these 2 arrays and store itint a new variable sum1 and execute it.

sum1= arr1+arr2

In [19]:
sum1


array([3, 5, 7, 9])

In [20]:
# inorder to know the type of variable used like as in spyder, there is n0 variable explorer in jupyter, so we use %whos

%whos

Variable   Type       Data/Info
-------------------------------
arr1       ndarray    4: 4 elems, type `int32`, 16 bytes
arr2       ndarray    4: 4 elems, type `int32`, 16 bytes
i          int        4
j          int        5
list1      list       n=4
list2      list       n=4
list3      list       n=4
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
sum1       ndarray    4: 4 elems, type `int32`, 16 bytes


In [21]:
## going to create a variable ,data2 which is list of lists

data2=[[1,2,3,4],[5,6,7,8]]

In [22]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [23]:
## now converting data2 into an array

arr3=np.array(data2)

In [25]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#it is printed as such ,cos our's is a 2D array

In [26]:
# inorder to check the dimension of array use the keyword as ndim

arr3.ndim
        #on executing it will show our array3 is a 2D array



2

In [27]:
# inorder to check the datatype of an array use dtype

arr3.dtype

dtype('int32')

In [28]:
#to find the shape of the array use keyword shape

arr3.shape

(2, 4)

In [29]:
#inorder to change data type of an array we can declare it initially

arr4= np.array(data2,dtype=float)

In [30]:
arr4

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [31]:
arr4.dtype

dtype('float64')

In [32]:
# on creating a new array  like this then it will execute like,

arr5=np.array(['1','2','3','5'])

In [33]:
arr5        ## it is given as a u1, which is a string datatype or unique. as it is given as""/'' and will be a string dtype always

array(['1', '2', '3', '5'], dtype='<U1')

In [34]:
# It can also be converted as integer dtype by,

arr6=np.array(arr5,dtype=int)

In [35]:
arr6

array([1, 2, 3, 5])

In [36]:
arr6.dtype     #to check it whether it is changed to an integer dtype

dtype('int32')

In [37]:
# for creating a list with range function...it will give/print 7 values from 0 to 6

list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [38]:
# in numpy for arranging/print continuous values called arange like range in list

np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [39]:
# to show arange function in numpy, will execute array from 4 till 19

arr7=np.arange(4,20)

In [40]:
arr7

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
# by giving one more value as step in the same arange function ,it will be like here given 2 as step,then incremented by 2 in it
## will give 3 invremented by 3 and so on

arr8=np.arange(4,20,2)

In [42]:
arr8

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
# the use of reshape function

arr9=arr8.reshape(4,2)

     #reshaping arr8 into a 4 by 2 array

In [44]:
arr9

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [45]:
#trying another reshape

arr10=arr8.reshape(2,4)           #reshaping into a 2 by 4 array


In [46]:
arr10

array([[ 4,  6,  8, 10],
       [12, 14, 16, 18]])

In [47]:
## about link space function

arr11=np.linspace(1,30,5)

In [48]:
arr11           # it will split values at equal intervals here 1 to 30 in 5 intervals

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [49]:
#trying same linspace again

arr12=np.linspace(1,12,4)

In [50]:
arr12       # Executed from 1 to 12 in 4 intervals

array([ 1.        ,  4.66666667,  8.33333333, 12.        ])